/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Acme/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Acme"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cluster/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    abbreviatedName?: string;
                    enableGtm?: boolean;
                    fqdn?: string;
                    id?: unknown;
                    instances?: components["schemas"]["HDBInstance"][];
                    name?: string;
                    organizationId?: unknown;
                    status?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Cluster"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    abbreviatedName?: string;
                    enableGtm?: boolean;
                    fqdn?: string;
                    id?: unknown;
                    instances?: components["schemas"]["HDBInstance"][];
                    name?: string;
                    organizationId?: unknown;
                    status?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cluster/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Cluster"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cluster/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsClusterIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsClusterIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ForgotPassword/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ForgotPassword"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/HDBInstance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    cluster?: components["schemas"]["Cluster"];
                    clusterFqdn?: string;
                    clusterId?: unknown;
                    cpu?: number;
                    createdByUserId?: unknown;
                    host?: components["schemas"]["Host"];
                    hostId?: string;
                    id?: unknown;
                    instanceFqdn?: string;
                    instanceType?: components["schemas"]["InstanceType"];
                    instanceTypeId?: unknown;
                    memory?: number;
                    name?: string;
                    operationsApiPort?: number;
                    operationsApiSecure?: boolean;
                    readIops?: number;
                    replicationFqdn?: string;
                    replicationHosts?: string[];
                    status?: string;
                    storage?: number;
                    tempPassword?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                    threads?: number;
                    useSharedProcess?: boolean;
                    version?: string;
                    writeIops?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HDBInstance"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HDBInstance"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    cluster?: components["schemas"]["Cluster"];
                    clusterFqdn?: string;
                    clusterId?: unknown;
                    cpu?: number;
                    createdByUserId?: unknown;
                    host?: components["schemas"]["Host"];
                    hostId?: string;
                    id?: unknown;
                    instanceFqdn?: string;
                    instanceType?: components["schemas"]["InstanceType"];
                    instanceTypeId?: unknown;
                    memory?: number;
                    name?: string;
                    operationsApiPort?: number;
                    operationsApiSecure?: boolean;
                    readIops?: number;
                    replicationFqdn?: string;
                    replicationHosts?: string[];
                    status?: string;
                    storage?: number;
                    tempPassword?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                    threads?: number;
                    useSharedProcess?: boolean;
                    version?: string;
                    writeIops?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/HDBInstance/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HDBInstance"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HDBInstance"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/HDBInstance/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsHDBInstanceIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsHDBInstanceIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Host/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    cloudFirewallId?: string;
                    cloudInstanceId?: string;
                    cloudInstanceType?: string;
                    fqdn?: string;
                    id?: string;
                    instances?: components["schemas"]["HDBInstance"][];
                    ipAddress?: string;
                    location?: components["schemas"]["Location"];
                    locationId?: unknown;
                    maxCPU?: number;
                    maxMemory?: number;
                    maxStorage?: number;
                    name?: string;
                    organizationIds?: unknown[];
                    status?: string;
                    updated?: number;
                    usedCPU?: number;
                    usedMemory?: number;
                    usedStorage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Host"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    cloudFirewallId?: string;
                    cloudInstanceId?: string;
                    cloudInstanceType?: string;
                    fqdn?: string;
                    id?: string;
                    instances?: components["schemas"]["HDBInstance"][];
                    ipAddress?: string;
                    location?: components["schemas"]["Location"];
                    locationId?: unknown;
                    maxCPU?: number;
                    maxMemory?: number;
                    maxStorage?: number;
                    name?: string;
                    organizationIds?: unknown[];
                    status?: string;
                    updated?: number;
                    usedCPU?: number;
                    usedMemory?: number;
                    usedStorage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Host/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Host"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Host/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsHostIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsHostIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/InstanceType/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    cpu?: number;
                    id?: unknown;
                    memory?: number;
                    readIops?: number;
                    selfHosted?: boolean;
                    threads?: number;
                    useSharedProcess?: boolean;
                    writeIops?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstanceType"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InstanceType"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    cpu?: number;
                    id?: unknown;
                    memory?: number;
                    readIops?: number;
                    selfHosted?: boolean;
                    threads?: number;
                    useSharedProcess?: boolean;
                    writeIops?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/InstanceType/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstanceType"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InstanceType"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/InstanceType/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsInstanceTypeIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsInstanceTypeIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Location/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    cloudProvider?: string;
                    id?: unknown;
                    lat?: number;
                    linodeMetadata?: components["schemas"]["LinodeMetadata"];
                    location?: string;
                    locationName?: string;
                    lon?: number;
                    regionIds?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    cloudProvider?: string;
                    id?: unknown;
                    lat?: number;
                    linodeMetadata?: components["schemas"]["LinodeMetadata"];
                    location?: string;
                    locationName?: string;
                    lon?: number;
                    regionIds?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Location/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Location"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Location/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsLocationIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsLocationIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Logout"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Organization/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    clusters?: components["schemas"]["Cluster"][];
                    createdByUserId?: unknown;
                    id?: unknown;
                    isUnpaid?: boolean;
                    name?: string;
                    roles?: components["schemas"]["OrganizationRole"][];
                    status?: string;
                    stripeCustomerId?: unknown;
                    subdomain?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    clusters?: components["schemas"]["Cluster"][];
                    createdByUserId?: unknown;
                    id?: unknown;
                    isUnpaid?: boolean;
                    name?: string;
                    roles?: components["schemas"]["OrganizationRole"][];
                    status?: string;
                    stripeCustomerId?: unknown;
                    subdomain?: string;
                    terminatedAt?: string;
                    terminatedByUserId?: unknown;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Organization/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Organization/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsOrganizationIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsOrganizationIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrganizationRole/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    id?: unknown;
                    organizationId?: unknown;
                    roleName?: string;
                    userIds?: unknown[];
                    users?: components["schemas"]["User"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationRole"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizationRole"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    id?: unknown;
                    organizationId?: unknown;
                    roleName?: string;
                    userIds?: unknown[];
                    users?: components["schemas"]["User"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrganizationRole/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationRole"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OrganizationRole"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrganizationRole/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsOrganizationRoleIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsOrganizationRoleIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Payment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Payment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ResendVerificationEmail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResendVerificationEmail"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ResetPassword/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPassword"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Role/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/User/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description search for records by the specified property name and value pairs */
        get: {
            parameters: {
                query?: {
                    email?: string;
                    firstname?: string;
                    id?: unknown;
                    isVerified?: boolean;
                    lastname?: string;
                    roles?: components["schemas"]["OrganizationRole"][];
                    salesforceId?: unknown;
                    status?: string;
                    terminatedAt?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new record auto-assigning a primary key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        /** @description primary key of new record */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        /** @description delete all the records that match the provided query */
        delete: {
            parameters: {
                query?: {
                    email?: string;
                    firstname?: string;
                    id?: unknown;
                    isVerified?: boolean;
                    lastname?: string;
                    roles?: components["schemas"]["OrganizationRole"][];
                    salesforceId?: unknown;
                    status?: string;
                    terminatedAt?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/User/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a record by its primary key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** @description delete a record with the given primary key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully processed request, no content returned to client */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/User/{id}.{property}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description used to retrieve the specified property of the specified record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                    property: PathsUserIdPropertyGetParametersPathProperty;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": PathsUserIdPropertyGetResponses200ContentApplicationJson;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/VerifyEmail/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description create or update the record with the URL path that maps to the record's primary key */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description primary key of record */
                    id: unknown;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VerifyEmail"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Acme: Record<string, never>;
        Cluster: {
            /** Format: String */
            abbreviatedName?: string;
            /** Format: Boolean */
            enableGtm?: boolean;
            /** Format: String */
            fqdn?: string;
            /** Format: ID */
            id?: unknown;
            instances?: components["schemas"]["HDBInstance"][];
            /** Format: String */
            name?: string;
            /** Format: ID */
            organizationId?: unknown;
            /** Format: String */
            status?: string;
            /** Format: Date */
            terminatedAt?: string;
            /** Format: ID */
            terminatedByUserId?: unknown;
        };
        ForgotPassword: Record<string, never>;
        HDBInstance: {
            cluster?: components["schemas"]["Cluster"];
            /** Format: String */
            clusterFqdn?: string;
            /** Format: ID */
            clusterId?: unknown;
            /** Format: Float */
            cpu?: number;
            /** Format: ID */
            createdByUserId?: unknown;
            host?: components["schemas"]["Host"];
            /** Format: String */
            hostId?: string;
            /** Format: ID */
            id?: unknown;
            /** Format: String */
            instanceFqdn?: string;
            instanceType?: components["schemas"]["InstanceType"];
            /** Format: ID */
            instanceTypeId?: unknown;
            /** Format: Int */
            memory?: number;
            /** Format: String */
            name?: string;
            /** Format: Int */
            operationsApiPort?: number;
            /** Format: Boolean */
            operationsApiSecure?: boolean;
            /** Format: Int */
            readIops?: number;
            /** Format: String */
            replicationFqdn?: string;
            replicationHosts?: string[];
            /** Format: String */
            status?: string;
            /** Format: Int */
            storage?: number;
            /** Format: String */
            tempPassword?: string;
            /** Format: Date */
            terminatedAt?: string;
            /** Format: ID */
            terminatedByUserId?: unknown;
            /** Format: Int */
            threads?: number;
            /** Format: Boolean */
            useSharedProcess?: boolean;
            /** Format: String */
            version?: string;
            /** Format: Int */
            writeIops?: number;
        };
        Host: {
            /** Format: String */
            cloudFirewallId?: string;
            /** Format: String */
            cloudInstanceId?: string;
            /** Format: String */
            cloudInstanceType?: string;
            /** Format: String */
            fqdn?: string;
            /** Format: String */
            id?: string;
            instances?: components["schemas"]["HDBInstance"][];
            /** Format: String */
            ipAddress?: string;
            location?: components["schemas"]["Location"];
            /** Format: ID */
            locationId?: unknown;
            /** Format: Int */
            maxCPU?: number;
            /** Format: Int */
            maxMemory?: number;
            /** Format: Int */
            maxStorage?: number;
            /** Format: String */
            name?: string;
            organizationIds?: unknown[];
            /** Format: String */
            status?: string;
            /** Format: Float */
            updated?: number;
            /** Format: Float */
            usedCPU?: number;
            /** Format: Float */
            usedMemory?: number;
            /** Format: Float */
            usedStorage?: number;
        };
        InstanceType: {
            /** Format: Int */
            cpu?: number;
            /** Format: ID */
            id?: unknown;
            /** Format: Int */
            memory?: number;
            /** Format: Int */
            readIops?: number;
            /** Format: Boolean */
            selfHosted?: boolean;
            /** Format: Int */
            threads?: number;
            /** Format: Boolean */
            useSharedProcess?: boolean;
            /** Format: Int */
            writeIops?: number;
        };
        LinodeMetadata: {
            /** Format: Int */
            datacenterId?: number;
        };
        Location: {
            /** Format: String */
            cloudProvider?: string;
            /** Format: ID */
            id?: unknown;
            /** Format: Float */
            lat?: number;
            linodeMetadata?: components["schemas"]["LinodeMetadata"];
            /** Format: String */
            location?: string;
            /** Format: String */
            locationName?: string;
            /** Format: Float */
            lon?: number;
            regionIds?: string[];
        };
        Login: Record<string, never>;
        Logout: Record<string, never>;
        Organization: {
            clusters?: components["schemas"]["Cluster"][];
            /** Format: ID */
            createdByUserId?: unknown;
            /** Format: ID */
            id?: unknown;
            /** Format: Boolean */
            isUnpaid?: boolean;
            /** Format: String */
            name?: string;
            roles?: components["schemas"]["OrganizationRole"][];
            /** Format: String */
            status?: string;
            /** Format: ID */
            stripeCustomerId?: unknown;
            /** Format: String */
            subdomain?: string;
            /** Format: Date */
            terminatedAt?: string;
            /** Format: ID */
            terminatedByUserId?: unknown;
        };
        OrganizationRole: {
            /** Format: ID */
            id?: unknown;
            /** Format: ID */
            organizationId?: unknown;
            /** Format: String */
            roleName?: string;
            userIds?: unknown[];
            users?: components["schemas"]["User"][];
        };
        Payment: Record<string, never>;
        ResendVerificationEmail: Record<string, never>;
        ResetPassword: Record<string, never>;
        Role: Record<string, never>;
        User: {
            /** Format: String */
            email?: string;
            /** Format: String */
            firstname?: string;
            /** Format: ID */
            id?: unknown;
            /** Format: Boolean */
            isVerified?: boolean;
            /** Format: String */
            lastname?: string;
            roles?: components["schemas"]["OrganizationRole"][];
            /** Format: ID */
            salesforceId?: unknown;
            /** Format: String */
            status?: string;
            /** Format: Date */
            terminatedAt?: string;
        };
        VerifyEmail: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAcme = components['schemas']['Acme'];
export type SchemaCluster = components['schemas']['Cluster'];
export type SchemaForgotPassword = components['schemas']['ForgotPassword'];
export type SchemaHdbInstance = components['schemas']['HDBInstance'];
export type SchemaHost = components['schemas']['Host'];
export type SchemaInstanceType = components['schemas']['InstanceType'];
export type SchemaLinodeMetadata = components['schemas']['LinodeMetadata'];
export type SchemaLocation = components['schemas']['Location'];
export type SchemaLogin = components['schemas']['Login'];
export type SchemaLogout = components['schemas']['Logout'];
export type SchemaOrganization = components['schemas']['Organization'];
export type SchemaOrganizationRole = components['schemas']['OrganizationRole'];
export type SchemaPayment = components['schemas']['Payment'];
export type SchemaResendVerificationEmail = components['schemas']['ResendVerificationEmail'];
export type SchemaResetPassword = components['schemas']['ResetPassword'];
export type SchemaRole = components['schemas']['Role'];
export type SchemaUser = components['schemas']['User'];
export type SchemaVerifyEmail = components['schemas']['VerifyEmail'];
export type $defs = Record<string, never>;
export enum PathsClusterIdPropertyGetParametersPathProperty {
    id = "id",
    organizationId = "organizationId",
    name = "name",
    abbreviatedName = "abbreviatedName",
    status = "status",
    instances = "instances",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId",
    fqdn = "fqdn",
    enableGtm = "enableGtm"
}
export enum PathsClusterIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    organizationId = "organizationId",
    name = "name",
    abbreviatedName = "abbreviatedName",
    status = "status",
    instances = "instances",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId",
    fqdn = "fqdn",
    enableGtm = "enableGtm"
}
export enum PathsHDBInstanceIdPropertyGetParametersPathProperty {
    id = "id",
    clusterId = "clusterId",
    cluster = "cluster",
    createdByUserId = "createdByUserId",
    hostId = "hostId",
    host = "host",
    status = "status",
    name = "name",
    instanceFqdn = "instanceFqdn",
    replicationFqdn = "replicationFqdn",
    clusterFqdn = "clusterFqdn",
    instanceTypeId = "instanceTypeId",
    instanceType = "instanceType",
    storage = "storage",
    useSharedProcess = "useSharedProcess",
    cpu = "cpu",
    memory = "memory",
    threads = "threads",
    readIops = "readIops",
    writeIops = "writeIops",
    version = "version",
    replicationHosts = "replicationHosts",
    tempPassword = "tempPassword",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId",
    operationsApiPort = "operationsApiPort",
    operationsApiSecure = "operationsApiSecure"
}
export enum PathsHDBInstanceIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    clusterId = "clusterId",
    cluster = "cluster",
    createdByUserId = "createdByUserId",
    hostId = "hostId",
    host = "host",
    status = "status",
    name = "name",
    instanceFqdn = "instanceFqdn",
    replicationFqdn = "replicationFqdn",
    clusterFqdn = "clusterFqdn",
    instanceTypeId = "instanceTypeId",
    instanceType = "instanceType",
    storage = "storage",
    useSharedProcess = "useSharedProcess",
    cpu = "cpu",
    memory = "memory",
    threads = "threads",
    readIops = "readIops",
    writeIops = "writeIops",
    version = "version",
    replicationHosts = "replicationHosts",
    tempPassword = "tempPassword",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId",
    operationsApiPort = "operationsApiPort",
    operationsApiSecure = "operationsApiSecure"
}
export enum PathsHostIdPropertyGetParametersPathProperty {
    id = "id",
    name = "name",
    status = "status",
    ipAddress = "ipAddress",
    fqdn = "fqdn",
    locationId = "locationId",
    location = "location",
    cloudInstanceType = "cloudInstanceType",
    cloudInstanceId = "cloudInstanceId",
    cloudFirewallId = "cloudFirewallId",
    maxStorage = "maxStorage",
    maxMemory = "maxMemory",
    maxCPU = "maxCPU",
    usedStorage = "usedStorage",
    usedMemory = "usedMemory",
    usedCPU = "usedCPU",
    organizationIds = "organizationIds",
    updated = "updated",
    instances = "instances"
}
export enum PathsHostIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    name = "name",
    status = "status",
    ipAddress = "ipAddress",
    fqdn = "fqdn",
    locationId = "locationId",
    location = "location",
    cloudInstanceType = "cloudInstanceType",
    cloudInstanceId = "cloudInstanceId",
    cloudFirewallId = "cloudFirewallId",
    maxStorage = "maxStorage",
    maxMemory = "maxMemory",
    maxCPU = "maxCPU",
    usedStorage = "usedStorage",
    usedMemory = "usedMemory",
    usedCPU = "usedCPU",
    organizationIds = "organizationIds",
    updated = "updated",
    instances = "instances"
}
export enum PathsInstanceTypeIdPropertyGetParametersPathProperty {
    id = "id",
    selfHosted = "selfHosted",
    useSharedProcess = "useSharedProcess",
    cpu = "cpu",
    memory = "memory",
    threads = "threads",
    readIops = "readIops",
    writeIops = "writeIops"
}
export enum PathsInstanceTypeIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    selfHosted = "selfHosted",
    useSharedProcess = "useSharedProcess",
    cpu = "cpu",
    memory = "memory",
    threads = "threads",
    readIops = "readIops",
    writeIops = "writeIops"
}
export enum PathsLocationIdPropertyGetParametersPathProperty {
    id = "id",
    regionIds = "regionIds",
    location = "location",
    locationName = "locationName",
    cloudProvider = "cloudProvider",
    lat = "lat",
    lon = "lon",
    linodeMetadata = "linodeMetadata"
}
export enum PathsLocationIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    regionIds = "regionIds",
    location = "location",
    locationName = "locationName",
    cloudProvider = "cloudProvider",
    lat = "lat",
    lon = "lon",
    linodeMetadata = "linodeMetadata"
}
export enum PathsOrganizationIdPropertyGetParametersPathProperty {
    id = "id",
    name = "name",
    createdByUserId = "createdByUserId",
    stripeCustomerId = "stripeCustomerId",
    isUnpaid = "isUnpaid",
    subdomain = "subdomain",
    status = "status",
    roles = "roles",
    clusters = "clusters",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId"
}
export enum PathsOrganizationIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    name = "name",
    createdByUserId = "createdByUserId",
    stripeCustomerId = "stripeCustomerId",
    isUnpaid = "isUnpaid",
    subdomain = "subdomain",
    status = "status",
    roles = "roles",
    clusters = "clusters",
    terminatedAt = "terminatedAt",
    terminatedByUserId = "terminatedByUserId"
}
export enum PathsOrganizationRoleIdPropertyGetParametersPathProperty {
    id = "id",
    roleName = "roleName",
    organizationId = "organizationId",
    userIds = "userIds",
    users = "users"
}
export enum PathsOrganizationRoleIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    roleName = "roleName",
    organizationId = "organizationId",
    userIds = "userIds",
    users = "users"
}
export enum PathsUserIdPropertyGetParametersPathProperty {
    id = "id",
    email = "email",
    isVerified = "isVerified",
    firstname = "firstname",
    lastname = "lastname",
    salesforceId = "salesforceId",
    status = "status",
    terminatedAt = "terminatedAt",
    roles = "roles"
}
export enum PathsUserIdPropertyGetResponses200ContentApplicationJson {
    id = "id",
    email = "email",
    isVerified = "isVerified",
    firstname = "firstname",
    lastname = "lastname",
    salesforceId = "salesforceId",
    status = "status",
    terminatedAt = "terminatedAt",
    roles = "roles"
}
export type operations = Record<string, never>;
