export const enum LocalStorageKeys {
	'AckedNotificationIds' = 'AckedNotificationIds',
	'ApiExplorerSettings' = 'ApiExplorerSettings',
	'ApiExplorerSidebarWidth' = 'ApiExplorerSidebarWidth',
	'ApplicationChatPosition' = 'ApplicationChatPosition',
	'ApplicationChatWidth' = 'ApplicationChatWidth',
	'ApplicationsSidebarWidth' = 'ApplicationsSidebarWidth',
	'ChatAlwaysApprovedTools' = 'ChatAlwaysApprovedTools',
	'DatabasesSidebarWidth' = 'DatabasesSidebarWidth',
	'LastUsedSignInMethod' = 'LastUsedSignInMethod',
	'LogsOrderReversed' = 'LogsOrderReversed',
	'RememberSignInMethod' = 'RememberSignInMethod',
	'ResizableModalSize' = 'ResizableModalSize',
	'SavedClusterState' = 'SavedClusterState',
	'Theme' = 'Theme',
}
