import { Plan } from '@/lib/api.patch';

// TODO: Once the server plans have deployment and performanceDescription, use them.
//       https://github.com/HarperDB/central-manager/pull/63
export const tempPlansMock: Plan[] = [
		{
			'id': 'fabric-block-level-0',
			'name': 'Fabric Managed Service Block Level 0',
			'status': 'ACTIVE',
			'locationsPerPlan': 2,
			'resourcesPerInstance': {
				'storageGb': 5,
				'memoryMb': 1024,
				'cpuCores': 1,
				'threads': 2,
				'readIopsLimit': 1000,
				'writeIopsLimit': 1000,
			},
			'deploymentType': 'free',
			'deploymentDescription': 'Free',
			'allowedRegionIds': ['global-1'],
			'priceUsd': 0,
			'performanceDescription': 'Basic (1K read/min)',
		},
		{
			'id': 'fabric-block-level-1',
			'name': 'Fabric Managed Service Block Level 1',
			'status': 'ACTIVE',
			'locationsPerPlan': 2,
			'resourcesPerInstance': {
				'storageGb': 10,
				'memoryMb': 2048,
				'cpuCores': 2,
				'threads': 4,
				'readIopsLimit': 3000,
				'writeIopsLimit': 2000,
			},
			'deploymentType': 'standard',
			'deploymentDescription': 'Standard',
			'priceUsd': 1,
			'performanceDescription': 'Medium (3K read/min)',
		},
		{
			'id': 'fabric-block-level-2',
			'name': 'Fabric Managed Service Level 2',
			'status': 'ACTIVE',
			'locationsPerPlan': 2,
			'resourcesPerInstance': {
				'storageGb': 20,
				'memoryMb': 4096,
				'cpuCores': 4,
				'threads': 8,
				'readIopsLimit': 20000,
				'writeIopsLimit': 10000,
			},
			'deploymentType': 'standard',
			'deploymentDescription': 'Standard',
			'priceUsd': 1,
			'performanceDescription': 'High (100K read/min)',
		},
		{
			'id': 'fabric-block-level-3',
			'name': 'Fabric Managed Service Level 3',
			'status': 'ACTIVE',
			'locationsPerPlan': 2,
			'resourcesPerInstance': {
				'storageGb': 1000,
				'memoryMb': 8192,
				'cpuCores': 12,
				'threads': 16,
				'readIopsLimit': 100000,
				'writeIopsLimit': 50000,
			},
			'deploymentType': 'standard',
			'deploymentDescription': 'Standard',
			'priceUsd': 1,
			'performanceDescription': 'Very High (500K read/min)',
		},
		{
			'id': 'fabric-block-cluster-dedicated-2',
			'name': 'Fabric Block Cluster Dedicated Node Level 2',
			'status': 'ACTIVE',
			'deploymentType': 'cluster-dedicated',
			'deploymentDescription': 'Dedicated for Cluster',
			'priceUsd': 1,
			'performanceDescription': 'High (100K read/min)',
		},
		{
			'id': 'fabric-block-cluster-dedicated-3',
			'name': 'Fabric Block Cluster Dedicated Node Level 3',
			'status': 'ACTIVE',
			'deploymentType': 'cluster-dedicated',
			'deploymentDescription': 'Dedicated for Cluster',
			'priceUsd': 1,
			'performanceDescription': 'Very High (500K read/min)',
		},
		{
			'id': 'fabric-block-cluster-dedicated-4',
			'name': 'Fabric Block Cluster Dedicated Node Level 4',
			'status': 'ACTIVE',
			'deploymentType': 'cluster-dedicated',
			'deploymentDescription': 'Dedicated for Cluster',
			'priceUsd': 1,
			'performanceDescription': 'Ultra (1MM read/min)',
		},
		{
			'id': 'fabric-block-org-dedicated-2',
			'name': 'Fabric Block Organization Dedicated Node Level 2',
			'status': 'ACTIVE',
			'deploymentType': 'org-dedicated',
			'deploymentDescription': 'Dedicated for Organization',
			'priceUsd': 1,
			'performanceDescription': 'High (100K read/min)',
		},
		{
			'id': 'fabric-block-org-dedicated-3',
			'name': 'Fabric Block Organization Dedicated Node Level 3',
			'status': 'ACTIVE',
			'deploymentType': 'org-dedicated',
			'deploymentDescription': 'Dedicated for Organization',
			'priceUsd': 1,
			'performanceDescription': 'Very High (500K read/min)',
		},
		{
			'id': 'fabric-block-org-dedicated-4',
			'name': 'Fabric Block Organization Dedicated Node Level 4',
			'status': 'ACTIVE',
			'deploymentType': 'org-dedicated',
			'deploymentDescription': 'Dedicated for Organization',
			'priceUsd': 1,
			'performanceDescription': 'Ultra (1MM read/min)',
		},
		{
			'id': 'self-hosted-2',
			'name': 'Self-Managed/On-Prem Level 2',
			'status': 'ACTIVE',
			'deploymentType': 'self-manage',
			'deploymentDescription': 'Manage Your Own Installation/Configuration',
			'priceUsd': 1,
			'performanceDescription': 'High (2 billion reads per block)',
		},
		{
			'id': 'self-hosted-3',
			'name': 'Self-Managed/On-Prem Level 3',
			'status': 'ACTIVE',
			'deploymentType': 'self-manage',
			'deploymentDescription': 'Manage Your Own Installation/Configuration',
			'priceUsd': 1,
			'performanceDescription': 'Very high (30 billion reads per block)',
		},
		{
			'id': 'self-hosted-4',
			'name': 'Self-Managed/On-Prem Level 4',
			'stripeProductId': '',
			'stripePriceId': '',
			'status': 'ACTIVE',
			'deploymentType': 'self-manage',
			'deploymentDescription': 'Manage Your Own Installation/Configuration',
			'priceUsd': 1,
			'performanceDescription': 'Ultra (60 billion reads per block)',
		},
	]
;
