export const templates = [
	{
		id: 'harper',
		name: 'Web + REST ORM',
		description: "Define your entities in schema.graphql, add your HTML/CSS/JS in web, and you're cooking!",
		tags: ['Harper', 'ORM', 'REST', 'GraphQL'],
		githubUrl: 'https://github.com/HarperFast/application-template/tree/fabric',
	},
	{
		id: 'harper-ts',
		name: 'TypeScript',
		description: 'The same Web + REST ORM from the first template, but with TypeScript sprinkled in.',
		tags: ['Harper', 'TypeScript', 'GraphQL'],
		githubUrl: 'https://github.com/HarperFast/application-template/tree/fabric-typescript',
	},
	// {
	// 	id: 'nextjs',
	// 	name: 'Next.js',
	// 	description: 'Full-stack React framework with API routes',
	// 	tags: ['React', 'SSR', 'API Routes'],
	// 	githubUrl: 'https://github.com/vercel/next.js',
	// },
	// {
	// 	id: 'angular',
	// 	name: 'Angular',
	// 	description: 'Enterprise-ready framework with TypeScript',
	// 	tags: ['TypeScript', 'SPA', 'Enterprise'],
	// 	githubUrl: 'https://github.com/angular/angular',
	// },
	// {
	// 	id: 'fastify',
	// 	name: 'Fastify',
	// 	description: 'Fast and low overhead web framework',
	// 	tags: ['Node.js', 'REST', 'Performance'],
	// 	githubUrl: 'https://github.com/fastify/fastify',
	// },
	// {
	// 	id: 'vector-search',
	// 	name: 'Vector Search',
	// 	description: 'AI-powered semantic search application',
	// 	tags: ['AI', 'Embeddings', 'Search'],
	// 	githubUrl: 'https://github.com/HarperDB/vector-search-template',
	// },
	// {
	// 	id: 'express',
	// 	name: 'Express',
	// 	description: 'Minimal and flexible Node.js framework',
	// 	tags: ['Node.js', 'REST', 'Minimal'],
	// 	githubUrl: 'https://github.com/expressjs/express',
	// },
	// {
	// 	id: 'graphql',
	// 	name: 'GraphQL API',
	// 	description: 'API with GraphQL query language',
	// 	tags: ['GraphQL', 'Apollo', 'API'],
	// 	githubUrl: 'https://github.com/graphql/graphql-js',
	// },
];
