name: Deploy Fabric Prod
on:
  workflow_dispatch:
jobs:
  deployToProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test
      - name: Run lint
        run: pnpm lint
      - name: Build staging
        run: pnpm build:staging
      - name: Install HarperDB
        run: npm install -g harperdb@4.6.0
      - name: Deploy to prod
        run: |
          rm -rf node_modules # Clean up node_modules, harper will install
          CLI_TARGET_USERNAME=${{ secrets.CLI_TARGET_USERNAME_PROD }} CLI_TARGET_PASSWORD='${{ secrets.HARPERDB_CLI_TARGET_PASSWORD_PROD }}' harperdb deploy target='${{ secrets.CLI_DEPLOY_TARGET_PROD }}' restart=true
