name: Deploy to Stage
on:
  workflow_dispatch:
  push:
    branches:
      - stage
  merge_group:
    branches:
      - stage

concurrency:
  group: stage-${{ github.event_name }}-${{ github.ref || github.head_ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  deployToStage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          node-version-file: '.nvmrc'
      - name: Disable Husky
        run: echo "HUSKY=0" >> $GITHUB_ENV
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test
      - name: Run lint
        run: pnpm lint
      - name: Verify stage can build
        run: pnpm build:stage
      - name: Semantic release
        if: ${{ github.event_name == 'push' }}
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine version tag for build
        if: ${{ github.event_name == 'push' }}
        run: |
          VERSION_TAG=$(git tag --points-at HEAD | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n1)
          if [ -z "$VERSION_TAG" ]; then
            VERSION_TAG="stage_${GITHUB_SHA:0:7}"
          fi
          echo "VITE_STUDIO_VERSION=$VERSION_TAG" >> $GITHUB_ENV
      - name: Build stage for release
        if: ${{ github.event_name == 'push' }}
        run: pnpm build:stage
      - name: Deploy to stage
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir deploy
          mv web deploy/
          cp -R deploy-template/* deploy/
          cd deploy
          CLI_TARGET_USERNAME=${{ secrets.CLI_TARGET_USERNAME }} CLI_TARGET_PASSWORD='${{ secrets.HARPERDB_CLI_TARGET_PASSWORD }}' pnpm harperdb deploy_component project=hdbms target='${{ secrets.CLI_DEPLOY_TARGET }}' restart=false replicated=true
