name: Deploy to Dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  deployToDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test
      - name: Run lint
        run: pnpm lint
      - name: Determine version tag for build
        run: |
          VERSION_TAG="v${GITHUB_SHA:0:7}"
          echo "$VERSION_TAG"
          echo "VITE_STUDIO_VERSION=$VERSION_TAG" >> $GITHUB_ENV
      - name: Build dev
        run: pnpm build:dev
      - name: Install HarperDB
        run: npm install -g harperdb@4.6.0
      - name: Deploy to dev
        run: |
          rm -rf node_modules # Clean up node_modules, harper will install
          CLI_TARGET_USERNAME=${{ secrets.CLI_TARGET_USERNAME_DEV }} CLI_TARGET_PASSWORD='${{ secrets.HARPERDB_CLI_TARGET_PASSWORD_DEV }}' harperdb deploy target='${{ secrets.CLI_DEPLOY_TARGET_DEV }}' restart=true
