name: Deploy Fabric Stage
on:
  workflow_dispatch:
jobs:
  deployToStage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build staging
        run: pnpm build:staging
      - name: Install HarperDB
        run: npm install -g harperdb@latest
      - name: Deploy to staging
        run: |
          rm -rf node_modules # Clean up node_modules, harper will install
          CLI_TARGET_USERNAME=HDB_ADMIN CLI_TARGET_PASSWORD='${{ secrets.HARPERDB_CLI_TARGET_PASSWORD }}' harperdb deploy target='https://studio-test-cm.harperdbcloud.com:9925' restart=true
